platform :ios, '7.0'

target 'BWiOSKitCollection' do

  pod 'Masonry'

  target 'BWiOSKitCollectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BWiOSKitCollectionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
